#!/bin/bash

ver="0.2"
# Ignore SIGINT (^C) and SIGTSTP (^Z)
trap "" 2 20
xrc=$HOME/.xinitrc
trc=$HOME/.tinitrc

# Source sldm configuration
if [[ -f /etc/sldmrc ]]
then
  source /etc/sldmrc
  count=0
  while [[ ${count} -lt ${#userconfig[@]} ]]
  do
    if [[ "${USER}" == "${userconfig[${count}]}" ]]
    then
      ${userconfig[${count}]}
    fi
    let count=count+1
  done
else
  echo -e "ERROR: A valid sldm configuration was not found!"
  echo -e "Logging out."
  sleep 2
  exit 1
fi

checkyesno() {
  local value=${!1}
  case $value in
    (true) return 0 ;;
    (false) return 1 ;;
    (*)
      echo "\$${1} is not set properly. Use 'true' or 'false'." >&2
      exit 1
    ;;
  esac
}

mainmenu() {
  # Generate main menu
  menu=$(
    count=0
    while [[ ${count} -lt ${#wmlist[@]} ]]
    do
      printf "%s\n" "${wmlist[${count}]}"
      let count=count+1
    done
    count=0
    while [[ ${count} -lt ${#tmlist[@]} ]]
    do
      printf "%s\n" "${tmlist[${count}]}"
      let count=count+1
    done
    if $(checkyesno allowconsole)
    then
      printf "%s\n" "console"
    fi
    if $(checkyesno allowshutdown)
    then
      printf "%s\n%s\n" "shutdown" "reboot"
    fi

  )

  choice=$(printf %s "$menu" |slmenu)
  if [[ $? != 0 ]]
  then
    exit 0
  fi

  case ${choice} in
    (console) exit 2 ;;
    (shutdown) ${shutdowncommand} ;;
    (reboot) ${rebootcommand} ;;
    (*) dispatch ;;
  esac
}

dispatch() {

  count=0
  while [[ ${count} -lt ${#wmlist[@]} ]]
  do
    if [[ "${choice}" == "${wmlist[${count}]}" ]]
    then
      # If X is already running and locktty=yes, activate it,
      # otherwise, increment.
      if $(checkyesno locktty)
      then # Verify display exists
        if [[ -n "${display//[0-9]/}" ]]
        then
          display=0
        fi
        # Activate existing X session
        if xdpyinfo -display :${display}.0 &> /dev/null
        then
          let tty=display+xtty
          chvt ${tty}
          exit 0
        fi
      else # Get the first empty display
        display=0
        while [[ ${display} -lt 7 ]]
        do
          if dpyinfo=$(xdpyinfo -display :${display}.0 2>&1 1>/dev/null)
          then
            let display=display+1
          elif [[ $dpyinfo = No\ protocol\ specified* ]]
          then
            # Display is in use by another user
            let display=display+1
          elif [[ $dpyinfo = Invalid\ MIT* ]]
          then
            let display=display+1
          else
            break
          fi
        done
      fi
      # Start X
      wm_bin="$xrc $choice"
      serverargs=":${display} ${serverargs} vt$((xtty+display))"
      if $(checkyesno loginshell)
      then
        setsid bash --login -c "startx $xrc $choice -- ${serverargs}" &> /dev/null &
      else
        setsid "startx $xrc $choice -- ${serverargs}" &> /dev/null &
      fi
      exit 0
    fi
    let count=count+1
  done

  count=0
  while [[ ${count} -lt ${#tmlist[@]} ]]
  do
    if [[ "${choice}" == "${tmlist[${count}]}" ]]
    then
      # Start T
      if $(checkyesno loginshell)
      then
        source $HOME/.profile
      fi
      exec $trc $choice
      exit 0
    fi
    let count=count+1
  done

}

mainmenu
